version: '3.8'

services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-api-test-runner
    networks:
      - api-test-network
    volumes:
      - ./target:/app/target

networks:
  api-test-network:
    driver: bridge
